name: Firmware Documentation

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create documentation directory
        run: |
          mkdir -p local/docs

      - name: Generate documentation for firmware
        uses: mattnotmitt/doxygen-action@v1

      - name: Archive all documentation
        uses: actions/upload-artifact@v1
        with:
          name: docs
          path: local/docs/

      - name: Deploy all documentation
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/master'
        with:
          BRANCH: gh-pages
          FOLDER: local/docs/html/
          TARGET_FOLDER: ./
